import type { Metadata } from "next";
import { Familjen_Grotesk, Inter } from "next/font/google";
import "./globals.scss";
import { ThemeProvider } from "./providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });
const familjenGrotest = Familjen_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={familjenGrotest.className}>
        <ThemeProvider>
          {children}

          <div className="blurCircle"></div>
          <div className="blurCircle"></div>
          <div className="blurCircle"></div>
        </ThemeProvider>
      </body>
    </html>
  );
}
